/// <reference types="next/image-types/global" />

// **Why this file exists, when `next-env.d.ts` already says the same line.**
//
// `next-env.d.ts` is generated by Next and is **gitignored** (`.gitignore`
// line 8), which is the framework's own default. CI never has it: `ci-web.yml`
// runs `pnpm typecheck` *before* `pnpm build`, and only the build would
// regenerate it.
//
// That was harmless until the first static image import. `next-image.d.ts` —
// pulled in by the reference above — is what declares `*.png`, `*.svg` and the
// rest as modules; without it `import shot from './radar-preview.png'` is
// `TS2307: Cannot find module`. So `/fundadores`'s hero passed locally, where
// the generated file exists from `next dev`, and failed in CI, where it does
// not. This file is tracked, so both see the same declarations.
//
// It is intentionally only the reference: everything else in `next-env.d.ts`
// (the route and root-param types) genuinely is build output and belongs to
// the generated file.
