"""The item -> catalogue code mapper (card B36). No network, no database.

Two kinds of test here and the distinction matters:

* **Conformance** -- the Python port must agree character-for-character with
  ``apps/web/lib/radar/product-key.ts``, which is the implementation the price
  band's measured accuracy was produced by. The fixture's expected values were
  generated BY the TypeScript, so a divergence in either file fails here.
* **Behaviour** -- the rules that are ours: exact before prefix, the
  disambiguation, and the one that decides whether a number may be computed at
  all (only an exact match may feed a band).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from licitaqui.catalog_match import (
    BAND_ELIGIBLE_RULES,
    CANDIDATE_WORDS,
    HEAD_WORDS,
    CatalogEntry,
    CatalogIndex,
    all_words,
    fold,
    product_head,
    resolve_description,
)

FIXTURE = Path(__file__).parent / "fixtures" / "catalog_head_conformance.json"


def _entry(code: int, name: str) -> CatalogEntry:
    """Build an entry the way the mirror job does -- through the real functions."""
    return CatalogEntry(
        code=code,
        name=name,
        head=tuple(product_head(name, CANDIDATE_WORDS)),
        words=tuple(all_words(name)),
    )


# --------------------------------------------------------------- conformance

def _cases() -> list[dict]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))["cases"]


def test_fixture_records_which_typescript_generated_it() -> None:
    """A conformance fixture with no provenance cannot be re-derived."""
    doc = json.loads(FIXTURE.read_text(encoding="utf-8"))
    assert doc["generated_from"] == "apps/web/lib/radar/product-key.ts"
    assert len(doc["source_sha"]) == 40
    assert len(doc["cases"]) >= 400


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["description"][:40] or "(empty)")
def test_port_matches_the_typescript(case: dict) -> None:
    """Every expected value here came out of product-key.ts, not out of Python."""
    assert product_head(case["description"]) == case["head"]
    assert product_head(case["description"], CANDIDATE_WORDS) == case["head_cap12"]
    assert all_words(case["description"]) == case["words"]


# ------------------------------------------------------------------ folding

def test_fold_strips_accents_and_punctuation_but_keeps_digits() -> None:
    assert fold("CAFÉ TORRADO E MOÍDO") == "cafe torrado e moido"
    assert fold("PAPEL A4 CX C/10") == "papel a4 cx c 10"
    assert fold("ÁGUA  SANITÁRIA   1L") == "agua sanitaria 1l"


def test_head_stops_at_the_first_attribute_and_drops_its_key() -> None:
    # "Material" is the attribute key, not part of the product name.
    assert product_head("CADEIRA ESCRITORIO, Material Estrutura: aco") == ["cadeira", "escritorio"]


def test_head_deduplicates_the_name_written_twice() -> None:
    twice = "Cadeira Escritório Cadeira Escritório, Material:"
    assert product_head(twice) == ["cadeira", "escritorio"]


def test_head_is_capped() -> None:
    assert len(product_head("alfa beta gama delta epsilon zeta")) == HEAD_WORDS


def test_single_letters_and_stopwords_are_not_head_words() -> None:
    assert product_head("CAFE E O A DE") == ["cafe"]


# ------------------------------------------------------- resolution rules

def test_exact_beats_prefix_even_when_a_prefix_is_longer_in_the_index() -> None:
    index = CatalogIndex([_entry(1, "PAPEL"), _entry(2, "PAPEL ALCALINO")])
    r = resolve_description(index, "PAPEL ALCALINO")
    assert (r.code, r.rule) == (2, "exact")


def test_longest_prefix_wins() -> None:
    index = CatalogIndex([_entry(1, "CADEIRA"), _entry(2, "CADEIRA RODAS")])
    r = resolve_description(index, "CADEIRA RODAS DOBRAVEL ALUMINIO")
    assert (r.code, r.rule, r.matched_words) == (2, "prefix", 2)


def test_a_head_shared_by_several_codes_is_decided_by_the_description() -> None:
    """The defect this rule exists for: `PAPEL A4 CX C/10` resolved to `PAPEL R`.

    Measured 2026-10-02: 4 026 active PDM names are a single word and 118 begin
    with PAPEL, so picking the lowest code is a coin flip.
    """
    index = CatalogIndex([_entry(10, "PAPEL R"), _entry(20, "PAPEL ALCALINO")])
    r = resolve_description(index, "PAPEL ALCALINO A4, GRAMATURA 75G/M2")
    assert r.code == 20
    assert r.candidates == 1  # distinct heads, so only one candidate per head


def test_ambiguous_head_counts_its_candidates() -> None:
    index = CatalogIndex([_entry(10, "SONDA"), _entry(20, "SONDA")])
    r = resolve_description(index, "SONDA")
    assert r.rule == "exact"
    assert r.candidates == 2


def test_disambiguation_is_deterministic_when_nothing_matches() -> None:
    index = CatalogIndex([_entry(30, "SONDA"), _entry(10, "SONDA"), _entry(20, "SONDA")])
    first = resolve_description(index, "SONDA").code
    for _ in range(5):
        assert resolve_description(index, "SONDA").code == first


def test_no_match_and_no_head_are_different_answers() -> None:
    index = CatalogIndex([_entry(1, "CADEIRA")])
    assert resolve_description(index, "FANTASIA MASCOTE LEAO").rule == "no_match"
    assert resolve_description(index, "a").rule == "no_head"
    assert resolve_description(index, None).rule == "no_head"


def test_an_empty_index_resolves_nothing_rather_than_raising() -> None:
    assert resolve_description(CatalogIndex([]), "CADEIRA").rule == "no_match"


# ------------------------------------------- the rule that gates the band

def test_only_an_exact_match_may_feed_a_band() -> None:
    """Sci's decision, 2026-10-02, on measured evidence.

    A prefix match's band is biased **+18.6%** against the real winning price
    while an exact match's is -3.6%, so the rule is not a preference.
    """
    assert {"exact"} == BAND_ELIGIBLE_RULES

    index = CatalogIndex([_entry(1, "CADEIRA"), _entry(2, "PAPEL ALCALINO")])

    # Head equal to the catalogue head -- the attribute tail is cut at the colon,
    # which is why this is exact while "PAPEL ALCALINO A4" (a 3-word head) is not.
    exact = resolve_description(index, "PAPEL ALCALINO, Gramatura: 75 g/m2")
    assert exact.rule == "exact" and exact.band_eligible is True

    # And the near miss, spelled out so the boundary is pinned rather than assumed.
    near = resolve_description(index, "PAPEL ALCALINO A4")
    assert near.rule == "prefix" and near.band_eligible is False

    prefix = resolve_description(index, "CADEIRA RODAS DOBRAVEL")
    assert prefix.rule == "prefix" and prefix.band_eligible is False

    none = resolve_description(index, "FANTASIA MASCOTE")
    assert none.rule == "no_match" and none.band_eligible is False


def test_a_resolution_that_contradicts_itself_cannot_be_constructed() -> None:
    """Stronger than checking `band_eligible`: the bad value cannot exist.

    The worker has no type checker, so the constructor is the nearest thing to
    the structural guarantee `LockedEvidence` gets from `tsc` in the web app.
    """
    import pytest as _pytest

    from licitaqui.catalog_match import Resolution

    # A code under a rule that means "nothing resolved".
    with _pytest.raises(ValueError, match="disagree"):
        Resolution(7, "no_match", 0, 0)
    # A rule that claims a match, with no code to show for it.
    with _pytest.raises(ValueError, match="disagree"):
        Resolution(None, "exact", 2, 1)
    # A rule nobody defined.
    with _pytest.raises(ValueError, match="unknown rule"):
        Resolution(7, "probably_fine", 1, 1)

    # And the two that are legitimate still construct.
    assert Resolution(7, "exact", 2, 1).band_eligible is True
    assert Resolution(None, "unknown_kind", 0, 0).band_eligible is False
