import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'
import { messages } from '@/lib/messages'
import { nextSteps } from './signup-form'
import { ShareSeat } from './share-seat'

/**
 * The confirmation's two new decisions, at the level a string of HTML can
 * actually settle — and **only** at that level.
 *
 * `vitest.config.mts` is `environment: 'node'`: there is no `window`, so no
 * clipboard, no origin, and `ShareSeat` renders the bare `/fundadores`
 * fallback rather than an absolute address. That rules out almost everything
 * worth knowing about a share control. Whether pressing it puts a usable link
 * on the clipboard, whether the address is legible rather than ellipsised, and
 * whether the seat stopped dominating the screen are all asserted in a real
 * browser in `e2e/journeys/fundadores.spec.ts` — and those are the tests that
 * matter, because the defects being fixed here were precisely a screen that
 * rendered approved words with nothing behind them. **A green file of unit
 * tests is what that screen already had.**
 *
 * So the test names below claim only what each assertion can carry.
 */

const out = renderToStaticMarkup(<ShareSeat />)
const confirmation = messages.founders.confirmation

describe('what the confirmation lists under "o que acontece agora"', () => {
  /*
   * Both settings of `WHATSAPP_WELCOME_IS_DELIVERED`, so the branch card E4
   * has to turn on is not untested code discovered on the day. The flag is
   * passed rather than read, which is the whole reason `nextSteps` takes a
   * parameter.
   */
  it('omits the "we sent you a WhatsApp" claim while nothing sends one', () => {
    const steps = nextSteps(false)
    expect(steps).not.toContain(confirmation.nextWhatsapp)
    // …and still answers the heading above it, rather than leaving it empty.
    expect(steps).toEqual([confirmation.nextOpening, confirmation.nextNothing])
  })

  it('restores it, first in the list, the day delivery is proven (card E4)', () => {
    expect(nextSteps(true)).toEqual([
      confirmation.nextWhatsapp,
      confirmation.nextOpening,
      confirmation.nextNothing,
    ])
  })

  it('defaults to the suppressed list, so the live page cannot claim it', () => {
    // No argument — this is what `/fundadores` actually renders today.
    expect(nextSteps()).not.toContain(confirmation.nextWhatsapp)
  })
})

describe('the founders share control', () => {
  it('takes its label from the catalogue instead of naming the action itself', () => {
    // Presence, not absence: this cannot prove no copy was invented anywhere
    // in the component, only that these two strings are the ones used.
    expect(out).toContain(confirmation.share)
    expect(out).toContain(messages.common.copy)
  })

  it('renders a real <button>, which is what makes the e2e focus assertion possible', () => {
    // Markup, deliberately: the *requirement* (reachable and operable by
    // keyboard) is asserted in the browser, where focus exists at all.
    expect(out).toContain('<button')
    expect(out).toContain('type="button"')
  })

  it('points aria-describedby at an id that exists in the same render', () => {
    // A dangling id is worse than none — it reads as covered and announces
    // nothing. The id is generated by `useId`, so this is not two literals
    // agreeing with each other.
    const described = /aria-describedby="([^"]+)"/.exec(out)?.[1]
    expect(described).toBeTruthy()
    expect(out).toContain(`id="${described}"`)
  })

  it('puts the address in the markup rather than only into the clipboard', () => {
    // Note what this does *not* show: with no `window`, the value here is the
    // relative fallback, so this would pass even if the component never built
    // an absolute URL. That the copied link is absolute — and identical to the
    // visible one — is asserted in the browser.
    expect(out).toContain('/fundadores')
  })
})
