"""The price band's arithmetic, ported from ``apps/web/lib/radar/price-band.ts``
(card B35).

## Why this is a port and not an import, and how the constants stay honest

The measured 56% hit rate and +0.2% median bias were produced by `priceBand()`
in that TypeScript module and by nothing else (approach doc §1). This file must
therefore agree with it, and the dangerous part is the three gate constants:
retyped as bare literals they become two numbers that can drift apart silently,
and nothing would fail.

**Two ways to prevent that were available, and the choice is deliberate:**

1. *Read the TypeScript at runtime.* Rejected. The worker image does not ship
   ``apps/web`` — it is a separate deployment (spec §13) — so a runtime read
   would make a Python job fail on a web-only file being absent, and would make
   the band depend on a parser at the moment it is least observable.
2. **Mirror the values here, and pin them with a test that parses
   ``price-band.ts`` and fails on any difference.** This is what
   ``tests/test_catalog_prices.py::test_the_gate_constants_have_not_drifted``
   does, and it is the same answer :mod:`licitaqui.catalog_match` already gives
   for `product-key.ts` (a conformance fixture generated from the TypeScript).
   The drift is caught at test time, where it is loud, rather than at refresh
   time, where it is a wrong number on a screen.

The test asserts it **extracted all four values** before comparing. A regex that
matched nothing and compared nothing would pass and prove nothing — `CLAUDE.md`
§4b's "a `replace` that matched nothing prints success".

## One place this deliberately differs from the TypeScript, and one that bit

* **Each purchase contributes two numbers, and they are not interchangeable.**
  `priceBand` takes each edital's **median** — ``percentile(rows, 0.5)``, which
  interpolates — because it only ever publishes quartiles taken *across*
  editais. `priceEvidence` takes the **lower-middle real row** —
  ``sorted[floor((n-1)/2)]`` — because it prints that figure beside that row's
  own words, so it has to be a price somebody paid.

  Those are two different functions of the same lots, and for a **two-row**
  purchase the difference is large: lots at R$ 10 and R$ 20 give a median of
  **15** and a lower-middle row of **10**, and at the measured 1.87 rows per
  purchase two-row purchases are the modal multi-row case. An earlier version of
  this module conflated them and computed the band from the real row, which put
  p25, median and p75 **below** what the back-test measured, in the dangerous
  direction for a number somebody bids against.

  So :func:`collapse_by_purchase` returns **both** — :class:`Representative`
  carries the row and the median together, because the lots are discarded at
  ingest and the choice is unrecoverable afterwards — and
  :class:`PurchasePrice`, the band's input, **has no field for the printed
  row's price at all**. The band therefore cannot be computed from the wrong
  number by a forgotten assignment; it would take a new field. That is the same
  structural argument `price-band.ts` makes for `LockedEvidence` having no price
  field, and it is here because the mistake has already been made once.

* **The age cutoff is a BRT calendar *day*, and the TypeScript's is a UTC
  instant. This is a real divergence, and it is the only one left.** (The
  boundary *within* a day is not: the comparison is strictly ``>`` the cutoff
  day, which is what the authority does for a midnight `dataCompra`, and the
  generated fixture pins it.) `priceBand`'s
  default ``now`` is ``new Date()`` — the server clock, UTC on our hosts — and
  :func:`compute_band` is called with
  :func:`licitaqui.catalog_prices.brt_today`. Between 00:00 and 03:00 BRT the
  two are on **different calendar days**, which is 3 hours in 24, or **12.36% of
  minutes** once the cutoff's own month arithmetic is applied; in those minutes
  the two implementations exclude different purchases.

  The BRT date is deliberate and is very probably the right choice here, because
  `dataCompra` *is* a Brazilian calendar date and comparing it against a UTC
  instant is the clock-mixing `CLAUDE.md` opens with. But a file whose purpose is
  to agree with the TypeScript must not disagree silently, and an earlier version
  of this list admitted only the time-of-day boundary and then claimed *"nothing
  else is reinterpreted"* — which was not true. The conformance fixture
  (:mod:`scripts.gen_price_band_conformance`) pins both sides with an **explicit**
  ``now``, so it tests the arithmetic rather than the clock, and this bullet is
  where the clock is written down instead.

Everything else is intended to be identical, and *intended* is the operative
word: the four constants are pinned to the TypeScript by a drift test, and the
arithmetic is pinned by a conformance fixture **generated by** `price-band.ts`
over adversarial lot sets — ties, even and odd counts, the cutoff boundary,
purchases split across windows. Before that fixture existed this file pinned the
constants to the source and the arithmetic only to numbers somebody had typed,
which is how both divergences above got in. `catalog_match.py` had already set
that precedent with 418 generated cases; this file cited it without following it.
"""

from __future__ import annotations

import calendar
import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import date
from decimal import Decimal, InvalidOperation

# -- the gates. Mirrored from price-band.ts; the drift test is what holds them --

#: Minimum **distinct purchases** before a band means anything.
#:
#: Mirrors `MIN_SAMPLE`. Note what changed with the source: the TypeScript counts
#: distinct *editais*, this counts distinct `id_compra`. Same discipline, same
#: reason — one procurement decision is one observation however many lots it was
#: split into.
#:
#: Measured 2026-10-02 and worth knowing before anybody tunes it: on this source
#: it is **not a binding gate at all**. Of 183 exact-matched items that got no
#: band, exactly **1** was refused for too few purchases; every exact-matched
#: code had ≥5, median 379, max 1 649.
MIN_SAMPLE = 5

#: Maximum inter-quartile spread as a fraction of the median. Mirrors
#: `MAX_SPREAD`.
#:
#: **This is where the product's real constraint lives.** 182 of those 183
#: refusals (99%) were this gate, because a PDM mixes products — **measured
#: 2026-10-02**, the same open-item probe as :data:`MIN_SAMPLE`'s figure and not
#: the CATMAT one below. That is the gate working: measured **2026-10-03**, a
#: separate probe, a CATMAT-level band buys 2.7× the coverage at a
#: 33% hit rate against the ~50% a correct quartile band scores (p<0.001), so
#: finer identity is not the answer. :data:`REFUSED_SPREAD_TOO_WIDE` exists so
#: this is a counted number rather than something discovered on a screen.
MAX_SPREAD = 0.5

#: How old a purchase may be and still count. Mirrors `MAX_AGE_MONTHS`.
#:
#: It is also the depth of a first-load window: a purchase older than this can
#: never feed a band, so asking for one is spent budget.
MAX_AGE_MONTHS = 18

#: How many purchases a thin rung prints. Mirrors `MAX_SAMPLES_SHOWN`.
#:
#: It is the reason only a handful of descriptions are stored per code (§4 of
#: the approach doc): the rungs below :data:`MIN_SAMPLE` print at most this
#: many, so storing more text than this is paying for something no screen can
#: show.
MAX_SAMPLES_SHOWN = 4


# -- the refusal vocabulary -------------------------------------------------

#: **Nothing is stored for this code inside the retention window.**
#:
#: Worded as a statement about our storage because that is all it can honestly
#: assert. The usual cause is the genuine one — ~6% of uniformly sampled needed
#: codes really have no rows in 18 months, measured and verified by re-asking
#: over 5 years — but a code whose last purchase has aged past
#: :data:`licitaqui.catalog_prices.PRUNE_AGE_MONTHS` has had its rows deleted
#: and lands here too, so a code can move from :data:`REFUSED_TOO_OLD` to this
#: one purely through the passage of time. Telling those two apart needs a
#: last-seen-purchase date the pinned schema has no column for; until it does,
#: this reason must not be read as "nobody has ever bought this".
#:
#: A walk that collected nothing while the API *reported* rows is a different
#: thing entirely and raises — see
#: :meth:`licitaqui.compras.ComprasClient.walk_prices`.
REFUSED_NO_ROWS = "no_rows"

#: Rows exist for this code, but none of them survived the
#: :data:`MAX_AGE_MONTHS` filter.
REFUSED_TOO_OLD = "too_old"

#: Fewer than :data:`MIN_SAMPLE` distinct purchases survived.
REFUSED_TOO_FEW_PURCHASES = "too_few_purchases"

#: IQR / median above :data:`MAX_SPREAD` — 99% of all refusals (182 of 183,
#: measured 2026-10-02).
REFUSED_SPREAD_TOO_WIDE = "spread_too_wide"

#: Every reason a `catalog_bands` row may carry. A refusal outside this set
#: cannot be constructed — see :class:`Refusal`.
#:
#: **Truncation is deliberately not in here.** A truncated walk produces no
#: knowledge about the code at all, so a row saying "no band today" would assert
#: something false while *superseding* yesterday's correct band: `catalog_bands`
#: is keyed `(kind, code, window_end)` and any reader takes the newest window,
#: so the band would vanish from the screen on the day the page cap bit.
#: :mod:`licitaqui.catalog_prices` counts truncation in `events` instead and
#: writes no band row — which is also what makes every reason in this set a
#: statement about a **sample** rather than about a read.
REFUSAL_REASONS = frozenset(
    {
        REFUSED_NO_ROWS,
        REFUSED_TOO_OLD,
        REFUSED_TOO_FEW_PURCHASES,
        REFUSED_SPREAD_TOO_WIDE,
    }
)


@dataclass(frozen=True, slots=True)
class Representative[RowT]:
    """What one purchase contributes: a real row **and** that purchase's median.

    Returned together by :func:`collapse_by_purchase` because they are two
    different functions of the same lots and both are needed — the lots are
    discarded at ingest, so computing one and not the other is unrecoverable.
    """

    #: The **lower-middle row by price**, `priceEvidence`'s choice. A price
    #: somebody actually paid, carrying its own unit, catalogue code and words,
    #: so a thin rung can print the figure beside the description it belongs to.
    row: RowT
    #: The purchase's **median**, `priceBand`'s choice, interpolating on an even
    #: number of lots. **This is what a band is computed from.** Not a price
    #: anybody paid, which is exactly why it is never printed.
    median: float


@dataclass(frozen=True, slots=True)
class PurchasePrice:
    """One purchase, as the **band's** input. One per `id_compra`.

    **There is deliberately no field for the printed row's price.** The band is
    `priceBand`'s arithmetic over per-purchase medians, and an earlier version
    of this module fed it the lower-middle real row instead — which for a
    two-row purchase is the minimum, so every quartile came out low. A type that
    cannot carry the wrong number means that mistake would have to be a new
    field rather than a forgotten assignment.

    It carries no supplier field either, and that is a rule rather than an
    optimisation (approach doc §4.1): every raw price row has `niFornecedor`,
    which is a CNPJ **or a CPF** for an individual supplier, against
    `CLAUDE.md`'s *never log CPF* and spec §12.
    """

    id_compra: str
    #: The purchase's median — `catalog_prices.unit_price_median`, never
    #: `unit_price`.
    median_price: float
    #: The calendar date of the purchase (`dataCompra`). ``None`` counts as
    #: fresh, exactly as a null `awardedOn` does in the TypeScript.
    purchased_on: date | None


@dataclass(frozen=True, slots=True)
class Band:
    """A band that passed every gate."""

    low: float
    median: float
    high: float
    n_purchases: int


@dataclass(frozen=True, slots=True)
class Refusal:
    """No band, and **why** — never a missing row.

    `refused_reason` is a column precisely so "spread too wide" is a number
    somebody can count, which is what turned 99%-is-spread from a guess into the
    dominant fact about the design.
    """

    reason: str
    n_purchases: int

    def __post_init__(self) -> None:
        # The worker has no type checker, so the constructor is the gate: a
        # reason outside the vocabulary cannot be written to the column at all.
        if self.reason not in REFUSAL_REASONS:
            raise ValueError(
                f"unknown refusal reason {self.reason!r}; "
                f"the vocabulary is {sorted(REFUSAL_REASONS)}"
            )


BandOutcome = Band | Refusal


def shift_months_back(moment: date, months: int) -> date:
    """``moment`` minus ``months``, with JavaScript's day-overflow behaviour.

    `priceBand` computes its cutoff with ``cutoff.setMonth(getMonth() - 18)``,
    and `setMonth` does not clamp: 2026-03-31 minus 18 months is **2024-10-01**,
    not 2024-09-30. Five dates a year differ, and the cutoff is a gate, so the
    port reproduces the roll-over rather than quietly clamping it.
    """
    index = (moment.year * 12 + (moment.month - 1)) - months
    year, month0 = divmod(index, 12)
    days_in_month = calendar.monthrange(year, month0 + 1)[1]
    if moment.day <= days_in_month:
        return date(year, month0 + 1, moment.day)
    overflow = moment.day - days_in_month
    # The roll always lands inside the same year: an overflow means the target
    # month is shorter than the source day, and December has 31 days — the most
    # any day-of-month can be — so the target can never be December. There is
    # deliberately no `month0 == 11` branch; it would be code nothing can reach.
    return date(year, month0 + 2, overflow)


def percentile(sorted_values: Sequence[float], fraction: float) -> float:
    """Linear-interpolating percentile, character for character the TypeScript's.

    Kept as its own function rather than folded into :func:`compute_band` so the
    drift test has something to compare against, and so a future `statistics`
    import cannot quietly substitute a different interpolation convention.
    """
    if len(sorted_values) == 1:
        return sorted_values[0]
    position = (len(sorted_values) - 1) * fraction
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return sorted_values[lower]
    return sorted_values[lower] + (sorted_values[upper] - sorted_values[lower]) * (position - lower)


#: The largest value ``numeric(16,4)`` can hold: 16 digits of precision, 4 of
#: them after the point.
#:
#: **A price above this is refused like any other non-price**, and that is not
#: tidiness. `is_usable_price` used to accept anything finite and positive, so a
#: junk ``1e15`` passed the filter, reached `executemany`, and Postgres raised
#: *numeric field overflow* — which rolls back the **whole code's** write, not
#: the one row. One bad value from the API would have cost a code its entire
#: refresh, repeatedly, and the migration's own comment says it left a positivity
#: check out precisely to avoid that failure mode.
MAX_NUMERIC_16_4 = 999_999_999_999.9999


def is_usable_price(value: object) -> bool:
    """`Number.isFinite(v) && v > 0`, the TypeScript's filter, plus the column.

    Applied at **ingest** as well as here, so a row that is not a price never
    reaches storage. That is what makes :data:`REFUSED_TOO_OLD` truthful: with
    non-prices already gone, age is the only thing the freshness filter can
    remove, so an empty fresh set means the rows are old rather than junk.

    Two additions to the TypeScript's three words, both for things that cannot
    happen in a browser:

    * **`Decimal` is accepted.** ``numeric`` comes back from psycopg as
      `Decimal`, and the first version tested ``isinstance(value, (int, float))``
      — so every stored price read back from the database would have failed this
      filter, every code would have been refused `too_old`, and the alarm would
      have stayed healthy because refusals are band rows. Two `float()` calls on
      the read path were all that stood between that and the whole feed.
    * **:data:`MAX_NUMERIC_16_4` is the ceiling**, because a value the column
      cannot hold is not a price we can store.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float, Decimal)):
        return False
    try:
        as_float = float(value)
    except (ValueError, OverflowError, InvalidOperation):
        # `Decimal('NaN')` and `Decimal('1E+1000')` both get here.
        return False
    return math.isfinite(as_float) and 0 < as_float <= MAX_NUMERIC_16_4


def collapse_by_purchase[RowT](
    rows: Sequence[RowT],
    *,
    purchase_of: Callable[[RowT], object],
    price_of: Callable[[RowT], object],
) -> list[Representative[RowT]]:
    """One :class:`Representative` per purchase: a real row **and** the median.

    A registro de preços split into 48 lots is one decision, and the measured
    median is 1.87 rows per purchase (mean 2.98, worst 47.8). Two independent
    reasons the collapse happens at ingest rather than at band time:

    * `priceBand` requires it anyway — row duplication compresses the IQR and
      disarms :data:`MAX_SPREAD`;
    * it is a **−47% storage reduction**, which is most of why the minimal
      tuple is 0.24 GB rather than 9.65 GB.

    Both numbers, because the two consumers want different ones and the lots
    are gone afterwards:

    * :attr:`Representative.row` is the **lower-middle row by price**, which is
      a figure somebody actually paid. A thin rung prints it beside that row's
      own words, and an interpolated R$ 15,00 between lots of R$ 10 and R$ 20
      would be a price nobody paid carrying a third row's description.
      `priceEvidence` makes exactly this choice, in exactly these words.
    * :attr:`Representative.median` is the purchase's **median**, interpolating,
      which is what `priceBand` takes and therefore what :func:`compute_band`
      must be given. Returning only the row is the defect this signature exists
      to prevent.

    Ties on price keep arrival order, so the result is reproducible and not
    merely deterministic-looking: the same payload must always collapse to the
    same row, or an idempotent refresh would rewrite storage for nothing.

    It is **generic over the row type on purpose.** The job collapses the full
    nine-column tuple it is about to store — it needs that row's own
    `item_number`, `supply_unit`, `catalog_item_code` and words, not just its
    price — while the band works on :class:`PurchasePrice`. One rule, written
    once; two shapes passing through it. A second implementation of the choice
    is exactly the shape this repository collects defects from.

    Rows whose price is not a usable price are dropped here, so a non-price
    never reaches storage.
    """
    grouped: dict[object, list[RowT]] = {}
    for row in rows:
        if not is_usable_price(price_of(row)):
            continue
        grouped.setdefault(purchase_of(row), []).append(row)

    collapsed: list[Representative[RowT]] = []
    for candidates in grouped.values():
        # `sorted` is stable, so equal prices keep arrival order.
        ordered = sorted(candidates, key=lambda row: float(price_of(row)))  # type: ignore[arg-type]
        prices = [float(price_of(row)) for row in ordered]  # type: ignore[arg-type]
        collapsed.append(
            Representative(
                # `priceEvidence`: `sorted[floor((n - 1) / 2)]`.
                row=ordered[(len(ordered) - 1) // 2],
                # `priceBand`: `percentile(sorted, 0.5)`, which interpolates. The
                # same `percentile` the quartiles use, so one purchase's median and
                # the band drawn across purchases agree on what a median is.
                median=percentile(prices, 0.5),
            )
        )
    return collapsed


def compute_band(purchases: Sequence[PurchasePrice], *, today: date) -> BandOutcome:
    """The band for one code, or the reason there is none.

    ``today`` is a **calendar date in BRT** — `dataCompra` is a Brazilian
    calendar date, and the database and the logs are UTC (`CLAUDE.md`'s clocks),
    so the caller converts once and this function never looks at a clock.

    ``purchases`` is **everything stored for the code**, old rows included. That
    is what lets the two empty-sample refusals say different things:
    :data:`REFUSED_TOO_OLD` when rows exist and the age gate removed them all,
    :data:`REFUSED_NO_ROWS` when there were none to begin with. Passing only the
    fresh ones would collapse both into the second, which reads as *nobody has
    ever bought this*.
    """
    cutoff = shift_months_back(today, MAX_AGE_MONTHS)
    fresh = [
        purchase
        for purchase in purchases
        # **Strictly after the cutoff day, not on or after it.** The
        # TypeScript's cutoff carries `now`'s time of day while a `dataCompra`
        # is midnight, so a purchase dated exactly on the cutoff day is `<` the
        # cutoff instant and the authority excludes it — confirmed by the
        # generated fixture's `cutoff` case, which bands on five purchases and
        # drops the one dated 2025-04-03 against a cutoff of 2025-04-03T12:00Z.
        # `>=` was here and silently admitted that day. The only `now` for which
        # the two disagree is exactly midnight UTC, which a real clock is not.
        if (purchase.purchased_on is None or purchase.purchased_on > cutoff)
        and is_usable_price(purchase.median_price)
    ]

    if not fresh:
        return Refusal(
            reason=REFUSED_TOO_OLD if purchases else REFUSED_NO_ROWS,
            n_purchases=0,
        )

    # One value per purchase. The ingest already collapsed, so this is normally a
    # no-op — but it goes through :func:`collapse_by_purchase` rather than a dict
    # assignment, because a dict would silently keep *whichever row came last*
    # if the invariant ever broke (a partly-applied prune, a hand-fixed row), and
    # row order out of Postgres is not stable across plans. `n_purchases` would
    # still look right while the band moved between runs for no visible reason.
    # One rule, written once, and it is deterministic.
    collapsed = collapse_by_purchase(
        fresh,
        purchase_of=lambda purchase: purchase.id_compra,
        price_of=lambda purchase: purchase.median_price,
    )
    n_purchases = len(collapsed)

    if n_purchases < MIN_SAMPLE:
        return Refusal(reason=REFUSED_TOO_FEW_PURCHASES, n_purchases=n_purchases)

    # **`.median`, the group's median — not the representative row.** The
    # authority groups rows per purchase and takes `percentile(rows, 0.5)` of
    # the group, so when a group has more than one row the answer is its median.
    # This read `.row.median_price` — the lower-middle row — on the argument
    # that the group is always a single row and the two therefore agree. They do
    # agree in that case, which is why nothing failed; but the whole point of
    # the guard is the case where the invariant broke, and there the two differ
    # in exactly the direction this card was written to remove. The defect class
    # had survived inside the guard against it.
    values = sorted(rep.median for rep in collapsed)
    median = percentile(values, 0.5)
    # `priceBand` guards `median <= 0` here. It cannot fire: every value cleared
    # `is_usable_price`, so the median of positives is positive. The guard is not
    # ported as a refusal reason because a reason nothing can produce is a string
    # nothing writes — and this repository has a rule about those.
    low = percentile(values, 0.25)
    high = percentile(values, 0.75)
    if (high - low) / median > MAX_SPREAD:
        return Refusal(reason=REFUSED_SPREAD_TOO_WIDE, n_purchases=n_purchases)

    return Band(low=low, median=median, high=high, n_purchases=n_purchases)
